export enum NotificationType {
  DOMAIN_SETUP = 'DOMAIN_SETUP',
  DOMAIN_ACCESS = 'DOMAIN_ACCESS',
  LIVE_SUPPORT = 'LIVE_SUPPORT',
  NAME_CHANGE = 'NAME_CHANGE',
  PASSWORD_CHANGE = 'PASSWORD_CHANGE',
  PLAN_UPGRADE = 'PLAN_UPGRADE',
  TEAM_INVITATION = 'TEAM_INVITATION',
  TEAM_ROLE_UPDATE = 'TEAM_ROLE_UPDATE',
  TEAM_MESSAGE = 'TEAM_MESSAGE',
  TRANSFER_REQUEST = 'TRANSFER_REQUEST',
  SHARED_CONVERSATION = 'SHARED_CONVERSATION'
} 